site_name: Essence
theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: indigo
  features:
    - navigation.indexes
    - navigation.tabs
  
nav:
  - Intro:
    - index.md
    - Installation: installation.md
  - Tutorials:
    - Basics:
      - Creating a Component: tutorials/first_component.md
      - State Managment: tutorials/state_managment.md
    - Advanced:
      - Using Fragments: tutorials/using_fragments.md
      - Renderize function: tutorials/renderize_function.md
      - Essence Properties: tutorials/properties.md
    - Hierarchy: tutorials/hierarchy.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences